import os

langs = {
    'de_DE': {
        'only-players': '"&cNur Spieler kÃ¶nnen diesen Befehl verwenden!"',
        'chunk-claim-success': '"&aDu hast diesen Chunk erfolgreich als &e%name%&a beansprucht!"',
        'chunk-claim-fail': '"&cChunk konnte nicht beansprucht werden."',
        'chunk-already-claimed-self': '"&eDu hast diesen Chunk bereits beansprucht."',
        'chunk-already-claimed-other': '"&cDieser Chunk gehört bereits einem anderen Spieler."',
        'worldguard-deny': '"&cDu kannst diesen Chunk nicht beanspruchen, da er eine WorldGuard Region überschneidet."',
        'chunk-unclaim-success': '"&aDu hast diesen Chunk erfolgreich freigegeben!"',
        'chunk-unclaim-fail': '"&cDir gehört dieser Chunk nicht oder er ist nicht beansprucht!"',
        'chunk-unowned': '"&eDieser Chunk gehört niemandem."',
        'chunk-owned-self': '"&aDieser Chunk gehört dir (&e%name%&a)."',
        'chunk-owned-other': '"&cDieser Chunk gehört %player% (&e%name%&c)."',
        'no-claims': '"&cDu hast keine beanspruchten Chunks."',
        'claims-header': '"&aDeine beanspruchten Chunks:"',
        'claim-entry': '"&6%index%. &fWelt: %world% &fBlockkoordinaten: X: %x%, Z: %z%"',
        'claim-group-entry': '"&6%index%. &e%name% &7(%count% Chunks)"',
        'claim-chunk-entry': '"  &7- &f%world% &7X: %x%, Z: %z%"',
        'visualize-start': '"&aDeine %count% beanspruchten Chunks werden für %seconds% Sekunden visualisiert."',
        'deny-break': '"&cDu kannst keine Blöcke in einem Chunk abbauen, der jemand anderem gehört."',
        'deny-place': '"&cDu kannst keine Blöcke in einem Chunk platzieren, der jemand anderem gehört."',
        'deny-interact': '"&cDu kannst in diesem Chunk nicht mit Objekten interagieren."',
        'deny-entity': '"&cDu kannst in diesem Chunk keine Entitäten beschädigen."',
        'lang-current': '"&aAktuelle Sprache: &e%locale%"',
        'lang-usage': '"&7Nutzung: /%label% set <locale>"',
        'lang-specify': '"&cBitte gib eine Sprache an. Beispiel: /%label% set de_DE"',
        'lang-unknown': '"&cUnbekannte Sprache: %locale%"',
        'lang-available': '"&7Verfügbar: %list%"',
        'lang-set': '"&aSprache auf &e%locale%&a gesetzt"',
        'gui-title-home': '"&2Chunk Einstellungen"',
        'gui-title-claims': '"&2Deine Chunks"',
        'gui-title-visualize': '"&3Chunk visualisieren"',
        'gui-title-delete': '"&4Chunk löschen"',
        'gui-title-language': '"&6Sprache"',
        'gui-item-claims': '"&6Chunks"',
        'gui-item-visualize': '"&bVisualisieren"',
        'gui-item-delete': '"&cLöschen"',
        'gui-item-language': '"&eSprache"',
        'gui-item-back': '"&eZurück"',
        'gui-title-claim-details': '"&2Chunk Details"',
        'gui-item-teleport': '"&aTeleportieren"',
        'teleport-no-permission': '"&cDu hast keine Berechtigung für den Teleport."',
        'gui-lore-block': '"&7Block: X: %x%, Z: %z%"',
        'gui-title-delete-confirm': '"&4Löschen bestätigen"',
        'gui-item-confirm': '"&cBestätigen"',
        'gui-item-cancel': '"&eAbbrechen"',
        'gui-lore-confirm': '"&7Bist du sicher? Dies kann nicht rückgängig gemacht werden."',
        'max-claims-reached': '"&cDu hast die maximale Anzahl an Chunks erreicht (%max%)."',
        'gui-item-particle': '"&dPartikel"',
        'gui-title-particle': '"&5Partikel wählen"',
        'gui-item-particle-reset': '"&eAuf Standard zurücksetzen"',
        'particle-set': '"&aPartikel auf &e%particle%&a gesetzt"',
        'particle-reset': '"&aPartikel auf Standard zurückgesetzt."',
        'admin-no-permission': '"&cDu hast keine Berechtigung für die Admin-Einstellungen."',
        'admin-gui-title-home': '"&4Admin-Einstellungen"',
        'admin-gui-item-max-claims': '"&6Max Chunks"',
        'admin-gui-item-language': '"&eStandardsprache"',
        'admin-gui-item-particle': '"&dStandardpartikel"',
        'admin-gui-item-reload': '"&cKonfiguration neu laden"',
        'admin-gui-title-max-claims': '"&6Max Chunks pro Spieler"',
        'admin-gui-title-language': '"&eServer-Standardsprache"',
        'admin-gui-title-particle': '"&dServer-Standardpartikel"',
        'admin-config-reloaded': '"&aKonfiguration erfolgreich neu geladen."',
        'admin-max-claims-set': '"&aMax Chunks pro Spieler auf &e%max%&a gesetzt."',
        'admin-language-set': '"&aServer-Standardsprache auf &e%locale%&a gesetzt."',
        'admin-particle-set': '"&aServer-Standardpartikel auf &e%particle%&a gesetzt."',
        'chunk-name-exists': '"&cDu hast bereits einen Chunk namens &e%name%&c."',
        'expand-usage': '"&cNutzung: /chunkexpand <name>"',
        'expand-not-found': '"&cDu hast keinen Chunk namens &e%name%&c."',
        'expand-success': '"&aChunk zu &e%name%&a hinzugefügt! Chunks: %total%."',
        'chunk-unclaim-name-success': '"&e%name%&a wurde freigegeben (%count% Chunks entfernt)."',
        'chunk-unclaim-name-fail': '"&cDu hast keinen Chunk namens &e%name%&c."',
        'gui-item-trust': '"&bVertraute Spieler"',
        'gui-title-trust': '"&3Vertraute Spieler"',
        'trust-added': '"&a%player% vertraut auf &e%name%&a."',
        'trust-removed': '"&c%player% nicht vertraut auf &e%name%&c."',
        'trust-no-online': '"&7Keine anderen Spieler sind online."',
        'gui-item-claim-settings': '"&6Chunk-Einstellungen"',
        'gui-title-claim-settings': '"&6Chunk-Einstellungen"',
        'gui-flag-mob-griefing': '"&eMob-Griefing Schutz"',
        'gui-flag-mob-spawning': '"&eMob-Spawning blockieren"',
        'gui-flag-mob-entry': '"&eMob-Eintritt blockieren"',
        'gui-flag-explosions': '"&eExplosionsschutz"',
        'gui-flag-pvp': '"&ePvP blockieren"',
        'gui-flag-enabled': '"&aAktiviert"',
        'gui-flag-disabled': '"&cDeaktiviert"',
        'gui-flag-click-toggle': '"&7Klicken zum Umschalten"',
        'flag-toggled': '"&e%flag% &7ist jetzt %state% &7auf &e%name%&7."',
        'deny-pvp': '"&cPvP ist in diesem Chunk deaktiviert."',
        'gui-flag-greeting-title': '"&eWillkommenstitel anzeigen"',
        'greeting-subtitle': '"&7Im Besitz von %player%"',
        'gui-item-rename': '"&eChunk umbenennen"',
        'rename-prompt': '"&aBitte tippe den neuen Namen für &e%name% &aim Chat, oder \'cancel\' zum abbrechen."',
        'rename-success': '"&aChunk erfolgreich in &e%name%&a umbenannt!"',
        'rename-cancel': '"&cUmbenennung abgebrochen."',
        'gui-flag-interact-chest': '"&eTruhen & Behälter schützen"',
        'gui-flag-interact-furnace': '"&eÖfen schützen"',
        'gui-flag-interact-stonecutter': '"&eWerkzeuge/Handwerk schützen"',
        'gui-flag-interact-door': '"&eTüren/Falltüren schützen"',
        'gui-flag-interact-redstone': '"&eRedstone Eingänge schützen"'
    },
    'pt_BR': {
        'only-players': '"&cApenas jogadores podem usar este comando!"',
        'chunk-claim-success': '"&aVocê reivindicou este chunk como &e%name%&a!"',
        'chunk-claim-fail': '"&cFalha ao reivindicar este chunk."',
        'chunk-already-claimed-self': '"&eVocê já reivindicou este chunk."',
        'chunk-already-claimed-other': '"&cEste chunk já foi reivindicado por outro jogador."',
        'worldguard-deny': '"&cVocê não pode reivindicar este chunk pois ele sobrepõe uma região WorldGuard."',
        'chunk-unclaim-success': '"&aVocê abandonou este chunk!"',
        'chunk-unclaim-fail': '"&cVocê não possui este chunk ou ele não está reivindicado!"',
        'chunk-unowned': '"&eEste chunk não tem dono."',
        'chunk-owned-self': '"&aEste chunk é seu (&e%name%&a)."',
        'chunk-owned-other': '"&cEste chunk pertence a %player% (&e%name%&c)."',
        'no-claims': '"&cVocê não tem chunks reivindicados."',
        'claims-header': '"&aSeus chunks reivindicados:"',
        'claim-entry': '"&6%index%. &fMundo: %world% &fCoordenadas do bloco: X: %x%, Z: %z%"',
        'claim-group-entry': '"&6%index%. &e%name% &7(%count% chunks)"',
        'claim-chunk-entry': '"  &7- &f%world% &7X: %x%, Z: %z%"',
        'visualize-start': '"&aVisualizando seus %count% chunks por %seconds% segundos."',
        'deny-break': '"&cVocê não pode quebrar blocos no chunk de outro jogador."',
        'deny-place': '"&cVocê não pode colocar blocos no chunk de outro jogador."',
        'deny-interact': '"&cVocê não pode interagir no chunk de outro jogador."',
        'deny-entity': '"&cVocê não pode danificar entidades no chunk de outro jogador."',
        'lang-current': '"&aIdioma atual: &e%locale%"',
        'lang-usage': '"&7Uso: /%label% set <locale>"',
        'lang-specify': '"&cEspecifique um idioma. Exemplo: /%label% set pt_BR"',
        'lang-unknown': '"&cIdioma desconhecido ou indisponível: %locale%"',
        'lang-available': '"&7Disponível: %list%"',
        'lang-set': '"&aIdioma definido para &e%locale%"',
        'gui-title-home': '"&2Configurações do Chunk"',
        'gui-title-claims': '"&2Seus Chunks"',
        'gui-title-visualize': '"&3Visualizar Chunk"',
        'gui-title-delete': '"&4Deletar Chunk"',
        'gui-title-language': '"&6Idioma"',
        'gui-item-claims': '"&6Chunks"',
        'gui-item-visualize': '"&bVisualizar"',
        'gui-item-delete': '"&cDeletar"',
        'gui-item-language': '"&eIdioma"',
        'gui-item-back': '"&eVoltar"',
        'gui-title-claim-details': '"&2Detalhes do Chunk"',
        'gui-item-teleport': '"&aTeleportar"',
        'teleport-no-permission': '"&cVocê não tem permissão para usar teleporte."',
        'gui-lore-block': '"&7Bloco: X: %x%, Z: %z%"',
        'gui-title-delete-confirm': '"&4Confirmar exclusão"',
        'gui-item-confirm': '"&cConfirmar"',
        'gui-item-cancel': '"&eCancelar"',
        'gui-lore-confirm': '"&7Tem certeza? Isso não pode ser desfeito."',
        'max-claims-reached': '"&cVocê alcançou seu número máximo de chunks (%max%)."',
        'gui-item-particle': '"&dPartícula"',
        'gui-title-particle': '"&5Escolher Partícula"',
        'gui-item-particle-reset': '"&eRedefinir Padrão"',
        'particle-set': '"&aPartícula definida para &e%particle%"',
        'particle-reset': '"&aPartícula redefinida para o padrão."',
        'admin-no-permission': '"&cVocê não tem permissão para acessar configurações de administrador."',
        'admin-gui-title-home': '"&4Config. Admin"',
        'admin-gui-item-max-claims': '"&6Máximo de Chunks"',
        'admin-gui-item-language': '"&eIdioma Padrão"',
        'admin-gui-item-particle': '"&dPartícula Padrão"',
        'admin-gui-item-reload': '"&cRecarregar Config."',
        'admin-gui-title-max-claims': '"&6Máx. de Chunks por Jogador"',
        'admin-gui-title-language': '"&eIdioma Padrão do Servidor"',
        'admin-gui-title-particle': '"&dPartícula Padrão do Servidor"',
        'admin-config-reloaded': '"&aConfigurações recarregadas."',
        'admin-max-claims-set': '"&aMáximo de chunks definido para &e%max%&a."',
        'admin-language-set': '"&aIdioma do servidor definido para &e%locale%&a."',
        'admin-particle-set': '"&aPartícula definida para &e%particle%&a."',
        'chunk-name-exists': '"&cVocê já tem um chunk chamado &e%name%&c."',
        'expand-usage': '"&cUso: /chunkexpand <nome>"',
        'expand-not-found': '"&cVocê não possui um chunk chamado &e%name%&c."',
        'expand-success': '"&aChunk adicionado a &e%name%&a! Total: %total%."',
        'chunk-unclaim-name-success': '"&aRenunciou &e%name%&a (%count% chunks)."',
        'chunk-unclaim-name-fail': '"&cVocê não tem um chunk chamado &e%name%&c."',
        'gui-item-trust': '"&bJogadores Confiáveis"',
        'gui-title-trust': '"&3Jogadores Confiáveis"',
        'trust-added': '"&a%player% agora é confiável em &e%name%&a."',
        'trust-removed': '"&c%player% não é mais confiável em &e%name%&c."',
        'trust-no-online': '"&7Nenhum outro jogador online."',
        'gui-item-claim-settings': '"&6Configurações do Chunk"',
        'gui-title-claim-settings': '"&6Configurações do Chunk"',
        'gui-flag-mob-griefing': '"&eProteção de Mobs"',
        'gui-flag-mob-spawning': '"&eBloquear Spawn de Mobs"',
        'gui-flag-mob-entry': '"&eBloquear Entrada de Mobs"',
        'gui-flag-explosions': '"&eProteção de Explosões"',
        'gui-flag-pvp': '"&eBloquear PvP"',
        'gui-flag-enabled': '"&aAtivado"',
        'gui-flag-disabled': '"&cDesativado"',
        'gui-flag-click-toggle': '"&7Clique para alterar"',
        'flag-toggled': '"&e%flag% &7agora está %state% &7em &e%name%&7."',
        'deny-pvp': '"&cPvP está desativado neste chunk."',
        'gui-flag-greeting-title': '"&eMostrar Título de Boas-vindas"',
        'greeting-subtitle': '"&7Propriedade de %player%"',
        'gui-item-rename': '"&eRenomear Chunk"',
        'rename-prompt': '"&aDigite o novo nome para &e%name% &ano chat, ou digite \'cancel\' para cancelar."',
        'rename-success': '"&aChunk renomeado para &e%name%&a com sucesso!"',
        'rename-cancel': '"&cRenomeação cancelada."',
        'gui-flag-interact-chest': '"&eProteger Baús e Contêineres"',
        'gui-flag-interact-furnace': '"&eProteger Fornalhas"',
        'gui-flag-interact-stonecutter': '"&eProteger Bancadas/Ferramentas"',
        'gui-flag-interact-door': '"&eProteger Portas/Alçapões"',
        'gui-flag-interact-redstone': '"&eProteger Entradas de Redstone"'
    },
    'ru_RU': {
        'only-players': '"&cТолько игроки могут использовать эту команду!"',
        'chunk-claim-success': '"&aВы успешно заприватили чанк под именем &e%name%&a!"',
        'chunk-claim-fail': '"&cОшибка привата чанка."',
        'chunk-already-claimed-self': '"&eВы уже заприватили этот чанк."',
        'chunk-already-claimed-other': '"&cЭтот чанк уже запривачен другим игроком."',
        'worldguard-deny': '"&cВы не можете заприватить этот чанк, так как он пересекается с регионом WorldGuard."',
        'chunk-unclaim-success': '"&aВы удалили свой приват этого чанка!"',
        'chunk-unclaim-fail': '"&cВы не владеете этим чанком!"',
        'chunk-unowned': '"&eЭтот чанк никем не запривачен."',
        'chunk-owned-self': '"&aЭтот чанк принадлежит вам (&e%name%&a)."',
        'chunk-owned-other': '"&cЭтот чанк принадлежит игроку %player% (&e%name%&c)."',
        'no-claims': '"&cУ вас нет заприваченных чанков."',
        'claims-header': '"&aВаши заприваченные чанки:"',
        'claim-entry': '"&6%index%. &fМир: %world% &fКоординаты: X: %x%, Z: %z%"',
        'claim-group-entry': '"&6%index%. &e%name% &7(%count% чанков)"',
        'claim-chunk-entry': '"  &7- &f%world% &7X: %x%, Z: %z%"',
        'visualize-start': '"&aОтображение ваших чанков (%count%) на %seconds% секунд."',
        'deny-break': '"&cВы не можете ломать блоки в чужом чанке."',
        'deny-place': '"&cВы не можете ставить блоки в чужом чанке."',
        'deny-interact': '"&cВы не можете использовать предметы в чужом чанке."',
        'deny-entity': '"&cВы не можете наносить урон сущностям в чужом чанке."',
        'lang-current': '"&aТекущий язык: &e%locale%"',
        'lang-usage': '"&7Использование: /%label% set <язык>"',
        'lang-specify': '"&cПожалуйста, укажите язык. Пример: /%label% set ru_RU"',
        'lang-unknown': '"&cНеизвестный язык: %locale%"',
        'lang-available': '"&7Доступно: %list%"',
        'lang-set': '"&aЯзык изменен на &e%locale%"',
        'gui-title-home': '"&2Настройки Чанка"',
        'gui-title-claims': '"&2Ваши Чанки"',
        'gui-title-visualize': '"&3Отображение Чанка"',
        'gui-title-delete': '"&4Удалить Чанк"',
        'gui-title-language': '"&6Язык"',
        'gui-item-claims': '"&6Чанки"',
        'gui-item-visualize': '"&bОтобразить"',
        'gui-item-delete': '"&cУдалить"',
        'gui-item-language': '"&eЯзык"',
        'gui-item-back': '"&eНазад"',
        'gui-title-claim-details': '"&2Информация о Чанке"',
        'gui-item-teleport': '"&aТелепортация"',
        'teleport-no-permission': '"&cУ вас нет прав для телепортации."',
        'gui-lore-block': '"&7Блок: X: %x%, Z: %z%"',
        'gui-title-delete-confirm': '"&4Подтвердите удаление"',
        'gui-item-confirm': '"&cПодтвердить"',
        'gui-item-cancel': '"&eОтмена"',
        'gui-lore-confirm': '"&7Вы уверены? Это действие необратимо."',
        'max-claims-reached': '"&cВы достигли максимума приватов (%max%)."',
        'gui-item-particle': '"&dЭффекты"',
        'gui-title-particle': '"&5Выбор эффектов"',
        'gui-item-particle-reset': '"&eСбросить по умолчанию"',
        'particle-set': '"&aЭффекты изменены на &e%particle%"',
        'particle-reset': '"&aЭффекты сброшены по умолчанию."',
        'admin-no-permission': '"&cУ вас нет прав администратора."',
        'admin-gui-title-home': '"&4Настройки Админа"',
        'admin-gui-item-max-claims': '"&6Макс. Чанков"',
        'admin-gui-item-language': '"&eЯзык по Умолчанию"',
        'admin-gui-item-particle': '"&dЭффект по Умолчанию"',
        'admin-gui-item-reload': '"&cПерезагрузить Конфиг"',
        'admin-gui-title-max-claims': '"&6Макс. Чанков на Игрока"',
        'admin-gui-title-language': '"&eЯзык сервера по умолчанию"',
        'admin-gui-title-particle': '"&dЭффект сервера по умолчанию"',
        'admin-config-reloaded': '"&aУспешная перезагрузка конфига."',
        'admin-max-claims-set': '"&aМаксимум чанков изменен на &e%max%&a."',
        'admin-language-set': '"&aЯзык по умолчанию изменен на &e%locale%&a."',
        'admin-particle-set': '"&aЭффект по умолчанию изменен на &e%particle%&a."',
        'chunk-name-exists': '"&cУ вас уже есть приват с именем &e%name%&c."',
        'expand-usage': '"&cИспользование: /chunkexpand <имя>"',
        'expand-not-found': '"&cУ вас нет привата с именем &e%name%&c."',
        'expand-success': '"&aЧанк добавлен в &e%name%&a! Всего чанков: %total%."',
        'chunk-unclaim-name-success': '"&aПриват &e%name%&a удален (%count% чанков)."',
        'chunk-unclaim-name-fail': '"&cУ вас нет привата с именем &e%name%&c."',
        'gui-item-trust': '"&bДоверенные игроки"',
        'gui-title-trust': '"&3Доверенные игроки"',
        'trust-added': '"&aИгрок %player% добавлен в &e%name%&a."',
        'trust-removed': '"&cИгрок %player% удален из &e%name%&c."',
        'trust-no-online': '"&7Нет других игроков онлайн."',
        'gui-item-claim-settings': '"&6Настройки Привата"',
        'gui-title-claim-settings': '"&6Настройки Привата"',
        'gui-flag-mob-griefing': '"&eЗащита от гриферства мобов"',
        'gui-flag-mob-spawning': '"&eБлокировать спавн мобов"',
        'gui-flag-mob-entry': '"&eБлокировать вход мобов"',
        'gui-flag-explosions': '"&eЗащита от взрывов"',
        'gui-flag-pvp': '"&eБлокировать PvP"',
        'gui-flag-enabled': '"&aВключено"',
        'gui-flag-disabled': '"&cОтключено"',
        'gui-flag-click-toggle': '"&7Нажмите для переключения"',
        'flag-toggled': '"&e%flag% &7теперь %state% &7в &e%name%&7."',
        'deny-pvp': '"&cPvP отключено в этом чанке."',
        'gui-flag-greeting-title': '"&eПоказывать Приветствие"',
        'greeting-subtitle': '"&7Владелец: %player%"',
        'gui-item-rename': '"&eПереименовать Приват"',
        'rename-prompt': '"&aВведите в чат новое имя для &e%name% &aили введите \'cancel\' для отмены."',
        'rename-success': '"&aПриват успешно переименован в &e%name%&a!"',
        'rename-cancel': '"&cПереименование отменено."',
        'gui-flag-interact-chest': '"&eЗащита Сундуков и Контейнеров"',
        'gui-flag-interact-furnace': '"&eЗащита Печей"',
        'gui-flag-interact-stonecutter': '"&eЗащита Станков/Верстаков"',
        'gui-flag-interact-door': '"&eЗащита Дверей/Люков"',
        'gui-flag-interact-redstone': '"&eЗащита Механизмов/Кнопок"'
    }
}

for lang_code, messages in langs.items():
    with open(f'src/main/resources/lang/messages_{lang_code}.yml', 'w', encoding='utf-8') as f:
        f.write(f'# Messages for {lang_code}\n')
        for k, v in messages.items():
            f.write(f'{k}: {v}\n')

print("Created DE, BR, RU langs")
