# ChunkClaimPlugin2 Configuration

# Maximum number of chunks a player can claim
max-claims-per-player: 10

# Messages
messages:
  chunk-claimed: "&aYou have successfully claimed this chunk!"
  chunk-unclaimed: "&eYou have unclaimed this chunk."
  claim-denied: "&cYou cannot claim this chunk."
  max-claims-reached: "&cYou have reached your maximum number of claims (%max%)."

# Particle settings
visualization:
  duration-seconds: 10
  particle-height: 100
  particle-spacing: 0.5
  particle-type: END_ROD

# Protection settings
protection:
  prevent-block-break: true
  prevent-block-place: true
  prevent-interactions: true