# ChunkClaimPlugin2 Configuration

# Language / Locale
# Set your language file to use (matches files in plugins/ChunkClaimPlugin2/lang/)
# Examples: en_US, es_ES
locale: en_US

# Maximum number of chunks a player can claim
max-claims-per-player: 10

# Messages
messages:
  # Optional: override messages by key here.
  # Example:
  # chunk-claim-success: "&aChunk claimed!"
  # max-claims-reached: "&cYou have reached your maximum number of claims (%max%)."

# Particle settings
visualization:
  duration-seconds: 10
  particle-height: 100
  particle-spacing: 0.5
  particle-type: END_ROD

# Protection settings
protection:
  prevent-block-break: true
  prevent-block-place: true
  prevent-interactions: true