name: ChunkClaimPlugin
version: '${version}'
main: org.ashin.chunkClaimPlugin2.ChunkClaimPlugin2
api-version: '1.21'
softdepend: [WorldGuard, WorldEdit]
commands:
  claimchunk:
    description: Claim the chunk you are standing in
    usage: /<command>
  unclaimchunk:
    description: Unclaim the chunk you are standing in
    usage: /<command>
  checkchunk:
    description: Check the ownership of the chunk you are standing in
    usage: /<command>
  infochunk:
    description: Get a list of your claimed chunks
    usage: /<command>
  visualizechunk:
    description: Visualize the borders of the chunk you are standing in
    usage: /<command>
  chunklang:
    description: View or set your language/locale
    usage: /<command> [get|list|set <locale>]
  chunksettings:
    description: Open the chunk settings GUI
    usage: /<command>
permissions:
  chunkclaimprotection.bypass:
    description: Allows bypassing chunk protection checks
    default: op
  chunkclaim.teleport:
    description: Allows using the Teleport action from the GUI
    default: op